/* the castle — C */
TI.registerArea({
    id: "castle",
    name: "the castle",
    shortName: "the castle",
    letter: "C",
    creature: "hollowguard",
    boss: "king",
    itemId: "rsword",
    memId: "m_castle",
    secretId: "torch",
    secretLine: "the treasury was emptied long ago — carefully, apologetically, with a note of ledger paper. one shelf was missed: pitch, wick, and wood.",
    map: [
        "##################",
        "#E...#.......1...#",
        "#....+...........#",
        "#.i..#....m......#",
        "#..2.#...........#",
        "########D#####+###",
        "#............#..s#",
        "#.....B......#...#",
        "#............#...#",
        "##################",
    ],
    enterText: "the gates stand open. they have stood open a long time. banners hang in strips, and the wind through the arrow-slits sounds like a house pretending to be asleep.",
    lockedText: "the throne room doors are barred from your side — which means somebody wanted to keep the king in, not you out. the guards still walking these halls hold the bar in place.",
    unlockText: "deep in the keep, a bar clatters to the floor. the throne room is open. something in there laughs, delighted.",
    itemLine: "across an armoury rack, one sword left of dozens: rusted, but the balance is still true.",
    regions: [
        { x0: 1, y0: 1, x1: 4, y1: 4, text: "the gatehouse. helmets are stacked in a corner, polished, arranged by size. someone has been tidying for a very long time." },
        { x0: 6, y0: 1, x1: 16, y1: 4, text: "the great hall. a banquet table runs its length, set for one. the food is fresh. the chair is pulled out." },
        { x0: 1, y0: 6, x1: 12, y1: 8, text: "the throne room. every wall is covered in names, scratched into the stone at throne height. they are all different. they are all yours." },
        { x0: 14, y0: 6, x1: 16, y1: 8, text: "the old treasury. emptied, swept, and signed for." },
    ],
    ambience: [
        "the sound of armour clanking can be heard down the hall.",
        "the wind whistles through the arrow-slits, high and thin.",
        "torn banners stir along the walls as you pass.",
        "dust sifts down from the rafters somewhere overhead.",
    ],
    ambienceLate: [
        "the armour down the hall keeps your pace. step for step.",
        "the torches in this hall are lit. you didn't light them.",
    ],
});
