/* the cave — V */
TI.registerArea({
    id: "cave",
    name: "the cave",
    shortName: "the cave",
    letter: "V",
    creature: "hollowecho",
    boss: "echo",
    itemId: "glowcap",
    memId: "m_cave",
    secretId: "torch",
    secretLine: "a supply nook, dry and squared-off, stocked by someone methodical: pitch, wick, wood. the torch is already half-assembled.",
    vision: 3.4,   /* the dark is real down here. carry a torch and it eases. */
    map: [
        "##################",
        "#.B..#....*......#",
        "#....#.1......*..#",
        "#....#...*.......#",
        "###D##...........#",
        "#.*.....m.*......#",
        "#.i.......*....s.#",
        "#....2...........#",
        "#...............E#",
        "##################",
    ],
    enterText: "the cave mouth exhales cold air in a slow rhythm, like breathing. the dark in here is thick, and your footsteps go in ahead of you and come back wrong.",
    lockedText: "the passage down is closed by a slab of stone that fits too well to be natural. on its face, one word, chiselled in your handwriting: LAST.",
    unlockText: "the slab marked LAST swings inward on a balance point, silent, counterweighted. built by an engineer. you feel the workmanship in your own hands.",
    itemLine: "a colony of glowcaps, pale and patient in the dark. you pick a cluster. the light comes with it.",
    regions: [
        { x0: 11, y0: 6, x1: 16, y1: 8, text: "the entry gallery. old torch brackets line the wall, all of them empty, all of them at exactly your reach." },
        { x0: 6, y0: 1, x1: 16, y1: 5, text: "the echo hall. drop a stone here and it lands twice. speak, and wait, and your own voice answers — from below, and slightly ahead of you." },
        { x0: 1, y0: 1, x1: 4, y1: 3, text: "the bottom of the cave. perfectly round, perfectly smooth, like a bubble in the rock. in the centre, the dark is standing up." },
    ],
    ambience: [
        "your footsteps echo twice down here. the second echo is heavier.",
        "water drips somewhere in the dark, slow and even, like a clock.",
        "the darkness ahead of you moves. or your eyes invent it. down here, there's no difference.",
        "cold air rises from below, slow and steady. like something breathing out.",
    ],
});
