/* the dark forest — F */
TI.registerArea({
    id: "forest",
    name: "the dark forest",
    shortName: "the forest",
    letter: "F",
    creature: "shadewisp",
    boss: "stag",
    itemId: "knife",
    memId: "m_forest",
    secretId: "glowcap",
    secretLine: "in the crook of a split trunk, a cache someone lined with moss: mushrooms that hold their own pale light.",
    map: [
        "##################",
        "#.T..T.......T..E#",
        "#..1....T........#",
        "#T......T....m...#",
        "#....T..T.T......#",
        "###D########+#####",
        "#.......#..T...i.#",
        "#...B...#..2...s.#",
        "#.......#........#",
        "##################",
    ],
    enterText: "the trees close behind you like a door. the light in here comes from nowhere in particular and doesn't reach the ground. it is very, very quiet.",
    lockedText: "the trees here grow in a wall, trunk against trunk. between two of them, an eye the size of your fist opens, considers you, and closes. not yet.",
    unlockText: "the wall of trees groans and leans apart, an inch at a time. an invitation. or an appointment.",
    itemLine: "driven into a stump, waiting: a hunting knife. the initials on the handle are yours.",
    regions: [
        { x0: 1, y0: 1, x1: 16, y1: 4, text: "the north wood. a path of white stones, laid by hand. they mark the way in. nobody has ever needed them to mark the way out." },
        { x0: 9, y0: 6, x1: 16, y1: 8, text: "a hollow glade. the grass grows in a perfect circle, and the trees around it all lean away." },
        { x0: 1, y0: 6, x1: 7, y1: 8, text: "the deep wood. between the trunks, pale shapes that are almost light. the silence here is the loud kind." },
    ],
    ambience: [
        "between two trunks, something pale stands very still. when you look again, it's gone.",
        "hoofbeats behind you. they stop when you stop — half a second late.",
        "no birds sing in here. they just watch.",
        "a branch snaps overhead. nothing falls.",
    ],
});
