/* the ruins — R */
TI.registerArea({
    id: "ruins",
    name: "the ruins",
    shortName: "the ruins",
    letter: "R",
    creature: "stonewarden",
    boss: "archivist",
    itemId: "shield",
    memId: "m_ruins",
    secretId: "tonic",
    secretLine: "a niche behind a fallen lintel, missed by every catalogue: a stoppered bottle, still sealed, labelled in your hand — 'for the next one.'",
    map: [
        "##################",
        "#E...□....□......#",
        "#..1......□..m...#",
        "#....□....□......#",
        "#□□□.□□□□□□□□□.□□#",
        "#..s.....2.......#",
        "#...□□□□□□□□D□□□□#",
        "#.i......□...B...#",
        "#........□.......#",
        "##################",
    ],
    enterText: "a city older than the count of years, folded down into the grass. the streets are still streets. something here still keeps office hours.",
    lockedText: "the archive doors are shut, and the stone says, in forty languages, RECORDS IN USE. the wardens are still filing. the wardens must finish filing.",
    unlockText: "the stone doors of the archive grind apart, and a voice from inside calls, pleasantly: \"come in, come in. you're expected.\"",
    itemLine: "a fallen warden's arm still grips it: a stone-faced shield. it is heavier than a wall and it wants to be held.",
    regions: [
        { x0: 1, y0: 1, x1: 16, y1: 3, text: "the plaza. toppled statues, every face carefully, lovingly chiselled off. except they all still look like somebody." },
        { x0: 1, y0: 5, x1: 16, y1: 5, text: "the processional way. every doorway has a name carved above it. you stop reading them after the third one." },
        { x0: 1, y0: 7, x1: 8, y1: 8, text: "the outer archive. shelves of stone tablets, indexed and cross-referenced. the subject of every single one is you." },
        { x0: 10, y0: 7, x1: 16, y1: 8, text: "the inner archive. lamplight. a desk. a chair for visitors, its cushion worn down by one particular shape of sitting." },
    ],
    ambience: [
        "stone grinds on stone, several streets over. filing.",
        "a tablet lies in your path, freshly placed. you step over it without reading it. it wanted you to read it.",
        "wind moves through the ruins in alphabetical order.",
    ],
});
