/* the swamp — S */
TI.registerArea({
    id: "swamp",
    name: "the swamp",
    shortName: "the swamp",
    letter: "S",
    creature: "boglurker",
    boss: "frog",
    itemId: "shard",
    memId: "m_swamp",
    secretId: "ration",
    secretLine: "half-sunk in the mud, a strongbox someone dragged this far and no farther. inside, wrapped in wax cloth: food that kept.",
    map: [
        "##################",
        "#..E....#........#",
        "#.......+....2...#",
        "#.≈≈....#........#",
        "#.≈≈.m..#......i.#",
        "#.......####D#####",
        "#..1....#........#",
        "#......s#...B....#",
        "#.......#........#",
        "##################",
    ],
    enterText: "the ground goes soft under your boots. the air is thick enough to chew. somewhere ahead, something enormous breathes in the water.",
    lockedText: "a wall of woven reeds and mud, packed deliberate and tight. whatever built it is still busy. the swamp is not done testing you.",
    unlockText: "somewhere deeper in, mud slides off mud. a way through has opened.",
    itemLine: "wedged in a rotted stump: an iron shard, sharp on three sides. torn off something much bigger.",
    regions: [
        { x0: 1, y0: 1, x1: 7, y1: 8, text: "dead reeds and standing water. the mud pulls at every step." },
        { x0: 9, y0: 1, x1: 16, y1: 4, text: "a drowned grove. the trees died standing up and never fell. bubbles rise in slow ones and twos." },
        { x0: 9, y0: 6, x1: 16, y1: 8, text: "the heart of the swamp. the water here is perfectly still and perfectly black, and something under it is looking up." },
    ],
    ambience: [
        "a low croak rolls across the water somewhere ahead.",
        "bubbles rise through the black water and pop, one by one.",
        "the reeds rustle in a wind you can barely feel.",
        "mist drifts between the dead trees in slow ribbons.",
    ],
    ambienceLate: [
        "there are bootprints in the mud ahead of you. the same tread as yours.",
        "the croak sounds again. it is exactly the same every time. exactly.",
    ],
});
